### ISSUE TITLE
代码会报错  

### ISSUE THREAD

**Issue by dcldclll** [HY-Org/hy.common.report#1]
为啥会报以下错误啊  大佬
XType.XML or XType.XD or XType.XSQL [org.hy.common.report.junit.brace.JU_Brace] is error ,maybe file or object is not find.
java.lang.RuntimeException: java.lang.NullPointerException: Source inputstream is null.
	at org.hy.common.xml.plugins.BaseInterface.init(BaseInterface.java:106)
	at org.hy.common.xml.annotation.XTypeAnno.init(XTypeAnno.java:58)
	at org.hy.common.xml.XJava.parserAnnotations(XJava.java:1410)
	at org.hy.common.xml.XJava.parserAnnotation(XJava.java:406)
	at org.hy.common.xml.XJava.parserAnnotation(XJava.java:390)
	at org.hy.common.report.junit.brace.JU_Brace.<init>(JU_Brace.java:39)
	at org.hy.common.report.junit.brace.main.main(main.java:13)
Caused by: java.lang.NullPointerException: Source inputstream is null.
	at org.hy.common.file.FileHelp.getContent(FileHelp.java:1808)
	at org.hy.common.file.FileHelp.getContent(FileHelp.java:1785)
	at org.hy.common.xml.plugins.BaseInterface.init(BaseInterface.java:97)
	... 6 more
java.lang.NullPointerException
	at org.hy.common.report.JavaToExcel.write(JavaToExcel.java:373)
	at org.hy.common.report.ReportHelp.toExcel(ReportHelp.java:184)
	at org.hy.common.report.junit.brace.JU_Brace.test_Normal(JU_Brace.java:72)
	at org.hy.common.report.junit.brace.main.main(main.java:14)

**Comment by HY-ZhengWei** [comment]
可能是没有引用XJava.jar，或者没编译成功，因为junit包下的类要自行编译一下的。
